project:
  type: website
  output-dir: gh-pages
  render:
    - "*.qmd"
    - "!testing/"

website:
  title: "EL"
  navbar:
    left:
      - CV.qmd
      - research.qmd
#      - text: Project
#        menu: 
#          - project1.qmd
#          - text: Project2
#          - project3.qmd

    right:
      - text: "{{< fa graduation-cap size=lg >}}"
        href: https://scholar.google.com/citations?user=IWLDxjsAAAAJ
      - text: "{{<fa brands linkedin size=lg >}}"
        href: https://ch.linkedin.com/in/erwin-lam-567586152
format:
  html:
    theme:
      light: flatly
    css: 
      - style.css
    link-external-newwindow: true

